### ISSUE TITLE
ERR wrong number of arguments for 'migrate' command

### ISSUE THREAD

**Issue by huacnlee** [yankov/redis-migrator#5] opened 2014-04-11 07:56 UTC
``` ruby
require 'redis_migrator'

old_redis_hosts = ["redis://127.0.0.1:6379"]
new_redis_hosts = ["redis://127.0.0.1:6380", "redis://127.0.0.1:6381", "redis://127.0.0.1:6382", "redis://127.0.0.1:6383", "redis://127.0.0.1:6384"]

migrator = Redis::Migrator.new(old_redis_hosts, new_redis_hosts)
migrator.run
```
- Redis 2.8.8
- Ruby 2.0.0
- redis-rb 3.0.4

``` bash
/usr/local/lib/ruby/gems/2.0.0/gems/redis-3.0.4/lib/redis/pipeline.rb:126:in `value': ERR wrong number of arguments for 'migrate' command (Redis::CommandError)
    from /usr/local/lib/ruby/gems/2.0.0/gems/redis-3.0.4/lib/redis/pipeline.rb:118:in `_set'
    from /usr/local/lib/ruby/gems/2.0.0/gems/redis-3.0.4/lib/redis/pipeline.rb:64:in `block in finish'
    from /usr/local/lib/ruby/gems/2.0.0/gems/redis-3.0.4/lib/redis/pipeline.rb:63:in `each'
    from /usr/local/lib/ruby/gems/2.0.0/gems/redis-3.0.4/lib/redis/pipeline.rb:63:in `each_with_index'
    from /usr/local/lib/ruby/gems/2.0.0/gems/redis-3.0.4/lib/redis/pipeline.rb:63:in `each'
    from /usr/local/lib/ruby/gems/2.0.0/gems/redis-3.0.4/lib/redis/pipeline.rb:63:in `map'
    from /usr/local/lib/ruby/gems/2.0.0/gems/redis-3.0.4/lib/redis/pipeline.rb:63:in `finish'
    from /usr/local/lib/ruby/gems/2.0.0/gems/redis-3.0.4/lib/redis/client.rb:121:in `block in call_pipeline'
    from /usr/local/lib/ruby/gems/2.0.0/gems/redis-3.0.4/lib/redis/client.rb:243:in `with_reconnect'
    from /usr/local/lib/ruby/gems/2.0.0/gems/redis-3.0.4/lib/redis/client.rb:119:in `call_pipeline'
    from /usr/local/lib/ruby/gems/2.0.0/gems/redis-3.0.4/lib/redis.rb:2031:in `block in pipelined'
    from /usr/local/lib/ruby/gems/2.0.0/gems/redis-3.0.4/lib/redis.rb:36:in `block in synchronize'
    from /usr/local/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
    from /usr/local/lib/ruby/gems/2.0.0/gems/redis-3.0.4/lib/redis.rb:36:in `synchronize'
    from /usr/local/lib/ruby/gems/2.0.0/gems/redis-3.0.4/lib/redis.rb:2027:in `pipelined'
    from /usr/local/lib/ruby/gems/2.0.0/gems/redis_migrator-0.1.1/lib/redis_migrator/redis_native_migrator.rb:21:in `block in migrate'
    from /usr/local/lib/ruby/gems/2.0.0/gems/redis_migrator-0.1.1/lib/redis_migrator/redis_native_migrator.rb:20:in `each'
    from /usr/local/lib/ruby/gems/2.0.0/gems/redis_migrator-0.1.1/lib/redis_migrator/redis_native_migrator.rb:20:in `migrate'
    from /usr/local/lib/ruby/gems/2.0.0/gems/redis_migrator-0.1.1/lib/redis_migrator.rb:53:in `migrate_keys'
    from /usr/local/lib/ruby/gems/2.0.0/gems/redis_migrator-0.1.1/lib/redis_migrator.rb:68:in `block (2 levels) in run'
```

**Comment by yankov** [comment] 2014-04-11 14:40
@redross can you please check it out?

**Comment by redross** [comment] 2014-04-11 14:47
Sure, I think the last PR was merged a bit too quickly :)

**Comment by redross** [comment] 2014-04-11 15:29
OK, reproduced this with redis-rb 3.0.4 will see what can be done.
(3.0.7 is giving a different error, but there is already a PR to fix it)

**Comment by redross** [comment] 2014-04-11 15:55
Ok, the reason for this is that proper "migrate" support was added since 3.0.5 (https://github.com/redis/redis-rb/blob/master/CHANGELOG.md)

Now there are two ways to fix this:
1. update redis requirement from => 3.0.0 to 3.0.5

``` diff
-  s.add_dependency('redis', '>= 3.0.0')
+  s.add_dependency('redis', '>= 3.0.5')
```

or
2. I could check for user redis version and change the migrate command to

``` diff
         old_node.pipelined do
-          node_keys.each { |key| old_node.migrate(key, new_node_options) }
+          migrate_key(old_node, key, new_node_options)
         end
       end
     end
+
+    def migrate_key(node, key, options)
+      if Redis::VERSION > '3.0.4'
+        node.migrate(key, destination_node_options)
+      else
+        node.migrate([options[:host], options[:port], key, options[:db], options[:timeout]])
+      end
+    end
   end
 end
```

@yankov what do You think?

@huacnlee would upgrading redis-rb version be an option for You? 

Also, 3.0.5+ won't work too until (https://github.com/yankov/redis-migrator/pull/7) is merged in.

**Comment by yankov** [comment] 2014-04-11 16:07
I think we can go with the second option if that works. Before 3.0.5 migrate was just dispatched through method_missing like other unimplemented commands, it's still should work as long as your redis server is > 2.6.

**Comment by huacnlee** [comment] 2014-04-11 16:12
That not important problem, I can fix that by modify source code in local.

在 2014年4月11日 星期五，下午11:55，Gintaras Sakalauskas 写道：

**Closed as completed** 2014-04-11 17:27 UTC
Labels: bug
